version: "3.9"

services:
  images_project:
    container_name: images_project_container
    build:
      context: .
      dockerfile: Dockerfile
    image: images_project_image:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app   # optional for local development hot reload
    command: uvicorn app.app:create_app --host 0.0.0.0 --port 8000 --reload
